name: Publish @fibricheck/javascript-sdk

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_FULL_READ_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Use Node LTS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Create .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
          echo "@fibricheck:registry=https://npm.pkg.github.com" >> .npmrc
      - run: yarn install
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGES_PUBLISH_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_PUBLISH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Create .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
          echo "@fibricheck:registry=https://npm.pkg.github.com" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_PUBLISH_TOKEN }}
      - run: yarn install
      - run: yarn build
      - run: yarn add-suffix
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: git tag -a v${{steps.extract_version.outputs.version}} -m "Tagging v${{steps.extract_version.outputs.version}}"
      - run: git push --tags && git push
      - run: yarn publish --registry https://npm.pkg.github.com/
